#!/usr/bin/env sh

if [ ! -d "$1" ]; then
    echo "arg1 dir \"$1\" does not exist"
    exit 1
fi

if [ ! -d "$2" ]; then
    echo "arg2 dir \"$2\" does not exist"
    exit 2
fi

if [ -z "$3" ]; then
    echo "Please provide the number of files to link"
    exit 3
fi

for i in $(seq -f "%02g" 1 "$3"); do
    ln -s "../../../$(echo "$1" | cut -d "/" -f 2-)/$i.png" "$2/$i.png"
    echo "Created link $i.png"
done
